### ISSUE TITLE
Make sure new videos will include timestamps

### ISSUE THREAD

**Issue by Almantask** [csinn/CSharp-From-Zero-To-Hero-v2#2]

**Comment by Almantask** [comment]
> The YouTube channel needs more care, but essentially your love :D
Updating the existing content would be really helpful for everyone since only small portion of people is able to be present in live streams. This is also important about ease of use of the content and makes it more understandable. Thus, people know where to look at better and it becomes easier to keep track of the content when we come to see next time.

**Comment by iirccm** [comment]
We started doing it through a new repository [here](https://github.com/gregory-butler/FromZeroToHero-TimeCodes)
Open to any suggestions and help
