### ISSUE TITLE
Answer questions in the end, not during the lesson

### ISSUE THREAD

**Issue by Almantask** [csinn/CSharp-From-Zero-To-Hero-v2#3]

**Comment by Almantask** [comment]
> So, from the previous lessons one thing that I found very distracting is when you try something on the fly. While I can't remember exactly if it was in response to a question or not. I felt that really took away from the lesson and sometimes even leads to bit of confusion. A good way to remedy this to ask everyone to write question down during the lesson and address them at the end, many questions are answered as you go through the lesson anyway.

**Comment by Joedmin** [comment]
I like this
