### ISSUE TITLE
Create a "run sheet"

### ISSUE THREAD

**Issue by Almantask** [csinn/CSharp-From-Zero-To-Hero-v2#4]
> I know you like the live coding approach, but I think having a "run sheet" premade would also help to smooth things out. What I mean by that is, have the code pre written, instead of copying and pasting, you can still live code it, but then you'll have a guide.

**Comment by Almantask** [comment]
What is a "run sheet"?

**Comment by daman92** [comment]
A "run sheet" is a pre-compiled list of commands. This serves as a guild and a convenient reference to keep one on track. These aren't uncommon in the system admin world, where one may have a limited time to do maintenance (especially command line systems like Linux servers). A run sheet allows for tasks to be outlined, with appropriate commands, before they are needed. Additional commands that might be needed but are not necessary can also be added (usually at the end). This pre exercise serves as a prototype for how the event will actually be executed. (and allows for contingency plans.)  In essence it's a combination of an outline and the commands needed for success.

**Comment by Almantask** [comment]
> A "run sheet" is a pre-compiled list of commands. This serves as a guild and a convenient reference to keep one on track. These aren't uncommon in the system admin world, where one may have a limited time to do maintenance (especially command line systems like Linux servers). A run sheet allows for tasks to be outlined, with appropriate commands, before they are needed. Additional commands that might be needed but are not necessary can also be added (usually at the end). This pre exercise serves as a prototype for how the event will actually be executed. (and allows for contingency plans.) In essence it's a combination of an outline and the commands needed for success.

So something like this:
> string input = Console.ReadLine() -> read user input
> bool isParsed = int.Parse(input, out int result) -> convert string to int
> Console.WriteLine("Done") -> print text to console

?

**Comment by daman92** [comment]
Sorry, I wrote an answer the other day and obviously didn't hit the button. Yes, that's fine. make it your own, I usually use descriptive headers, and put the parts I need in more detail like commands on a separate line so it's easy to see.

Something like this:

introduce user input
> string input = Console.ReadLine() 
> bool isParsed = int.Parse(input, out int result) 
> Console.WriteLine("Done") 

remember to explain "out" keyword.

Show refactoring.

Just a guided way to keep your thoughts and remember all the key points you want to hit.
